quamotion/remoteviewing

RemoteViewing.Example/MainForm.Designer.cs, RemoteViewing.Tests/Properties/AssemblyInfo.cs, RemoteViewing.Tests/RemoteViewing.Tests.csproj, RemoteViewing.Tests/VncClientTests.cs, RemoteViewing.Tests/packages.config, RemoteViewing.Windows.Forms/VncBitmap.cs, RemoteViewing.Windows.Forms/VncControl.cs, RemoteViewing.sln, RemoteViewing/Vnc/VncClient.Framebuffer.cs, RemoteViewing/Vnc/VncClient.cs, RemoteViewing/Vnc/VncClientConnectOptions.cs, RemoteViewing/Vnc/VncPixelFormat.cs
Hi,
thats my first pull request. I've added these features:
- added possibility to show local cursor when remote cursor is activated
-> In the demo application, the local and the remote cursor are shown now. But i've added a property and the default behavior is like it was before (not showing the local cursor)
- added down scaling functionality for windows forms control 
-> When you resize the demo application, the remote view shrinks automatically according to the size of the window
- added OnDemandMode option and GetFramebuffer function
-> disables the poll thread and provides the possibility to get framebuffer updates in a synchronous way
- some additional changes to maximize reuse and flexibility
Best regards,
Tom
=> Local Cursor, down scaling and "on demand" mode

RemoteViewing.AspNetCore/VncHandler.cs, RemoteViewing.AspNetCore/VncMiddleware.cs, RemoteViewing.AspNetCore/VncMiddlewareExtensions.cs, RemoteViewing/Vnc/Server/IVncFramebufferCache.cs, RemoteViewing/Vnc/Server/IVncServerSession.cs, RemoteViewing/Vnc/Server/VncFramebufferCache.cs, RemoteViewing/Vnc/Server/VncServerSession.cs
* Support passing a custom subclass of `VncServerSession` in the ASP.NET Core `VncMiddleware`.
* Create a `IVncServerSession` interface, so that `VncFramebufferCache` can be unit-tested easily.
=> Additional flexibility in subclassing/mocking VncServerSession

RemoteViewing.AspNetCore/WebSocketStream.cs, RemoteViewing/Vnc/Server/VncServerSession.cs
This can happen when the connection is an ASP.NET Core WebSocket and the server is shutting down
=> Handle a TaskCancelledException in VncServerSession. 

RemoteViewing/RemoteViewing.csproj, RemoteViewing/VncLogger.cs
Other users may find it useful, and it comes at the cost of a tiny dependency.
=> Move VncLogger (which wraps around ILogger) to the RemoteViewing

RemoteViewing.AspNetCore/RemoteViewing.AspNetCore.csproj, RemoteViewing.Windows.Forms/RemoteViewing.Windows.Forms.csproj, RemoteViewing/RemoteViewing.csproj, appveyor.yml
Use the PackageLicenseExpression tag to set the license of the NuGet package. Also publish source packages.
=> Update license information

RemoteViewing/Vnc/Server/IVncServerSession.cs
Makes it easier to mock `VncServerSession` objects in unit tests.
=> Add more members to the IVncServerSession interface

RemoteViewing.Tests/VncServerSessionTests.cs, RemoteViewing/Vnc/Server/VncServerSession.cs
It can happen that capturing the frame buffer source fails. This would currently stop syncing the screen.
This PR ignores failed captures.
=> Handle capture failures from the frame buffer source

RemoteViewing.Tests/TestStream.cs, RemoteViewing.Tests/VncServerSessionTests.cs, RemoteViewing/Vnc/Server/VncServerSession.cs, RemoteViewing/Vnc/VncStream.cs
Version 3.8 of the RFB protocol mandates you send a string explaining the authentication failure to the client. The current implementation did not do this, resulting in timeouts and other undefined behavior.
=> Fix protocol violations in VncServerSession.NegotiateSecurity

RemoteViewing.AspNetCore/RemoteViewing.AspNetCore.csproj, RemoteViewing.NoVncExample/RemoteViewing.NoVncExample.csproj, RemoteViewing.NoVncExample/Startup.cs, RemoteViewing.Windows.Forms/RemoteViewing.Windows.Forms.csproj, RemoteViewing.Windows.Forms/Server/VncScreenFramebufferSource.cs, RemoteViewing.Windows.Forms/VncControl.Designer.cs, RemoteViewing.Windows.Forms/VncControl.cs, RemoteViewing.Windows.Forms/VncKeysym.cs, RemoteViewing/RemoteViewing.csproj, appveyor.yml
Remove dependencies which are not required on netstandard2.1 to simplify the dependency graph on .NET Core
=> Target netstandard2.1

appveyor.yml
Not sure what broke (there's an update to a new version of the .NET Core SDK, so it's most likely that). We're moving to Azure Pipelines anyway, so a quick workaround to keep builds going should be fine.
=> Try with the previous AppVeyor image

RemoteViewing.Tests/Vnc/Server/RawEncoderTests.cs, RemoteViewing/Vnc/Server/RawEncoder.cs, RemoteViewing/Vnc/Server/VncEncoder.cs, RemoteViewing/Vnc/Server/VncServerSession.cs
This PR adds the `VncEncoder` class, which is responsible for receiving a raw (uncompressed) rectangle, encoding it and sending it to the client.
Currently only `VncRawEncoder` is implemented, which makes it a no-op. Tight encoding will come in a follow-up PR.
=> Add support for multiple VNC encodings

RemoteViewing/Vnc/VncEncoding.cs
This doesn't add any _support_ for these encodings, but merely adds them to the `VncEncoding` enumeration.
This makes the debugger recognize these values, and makes it slightly easier to work with them.
The `VncEncoding` enumeration now recognizes all encodings supported by noVNC, TightVNC and RealVNC.
=> Add known (pseudo-)encodings to the VncEncoding enumeration.

RemoteViewing.Tests/Vnc/VncPixelFormatTests.cs, RemoteViewing/Vnc/VncPixelFormat.cs
- Use auto properties
- Use standard argument validation methods
- Accept a bit depth of 8, as this is with RealVNC will propose first
- Add unit tests
The most important effect of this PR is a RealVNC client can now connect to the demo application. This will help us to validate the various encoders with three clients:
- noVNC
- RealVNC
- TightVNC
=> VncPixelFormat improvements

RemoteViewing.ServerExample/Program.cs, RemoteViewing.ServerExample/RemoteViewing.ServerExample.csproj, RemoteViewing/Vnc/VncPixelFormat.cs
- Listen on `127.0.0.1` instead of `0.0.0.0` so the app doesn't require elevated permissions
- Use a dummy framebuffer source instead of the screen, so it works on headless servers, too.
- Allow 6bpp pixel formats for VNC compatibility.
=> Simplify console application

RemoteViewing.Tests/Vnc/Server/TightEncoderTests.cs, RemoteViewing/RemoteViewing.csproj, RemoteViewing/Vnc/Server/TightCompressionControl.cs, RemoteViewing/Vnc/Server/TightEncoder.cs
Adds a very basic implementation of a Tight encoder, which _only_ supports zlib compression using a _single_ zlib stream which is _always_ reset (i.e. for every rectangle).
Tested to be compatible with noVNC.
=> Add Tight encoder

RemoteViewing.Tests/VncServerSessionTests.cs, RemoteViewing/Vnc/Server/VncEncoder.cs, RemoteViewing/Vnc/Server/VncServerSession.cs, RemoteViewing/Vnc/VncEncoding.cs
The encoders are re-evaluated every time when a client sends the list of supported encoders, or changes the pixel format, and the best match is used for the remainder of the session.
=> VncServerSession: Support using encoders

RemoteViewing/Vnc/Server/VncMessageType.cs, RemoteViewing/Vnc/Server/VncServerSession.cs
- Log all FramebufferUpdateRequest details at Debug instead of Info level
- Avoid spamming the log at Info level when the same request is handled repeatedly.
=> Reduce logging verbosity at the Info level

RemoteViewing.Tests/RemoteViewing.Tests.csproj, RemoteViewing.Tests/Vnc/Server/TightEncoderTests.cs, RemoteViewing/RemoteViewing.csproj, RemoteViewing/Vnc/Server/IVncServerSession.cs, RemoteViewing/Vnc/Server/TightEncoder.cs, RemoteViewing/Vnc/Server/VncServerSession.cs, RemoteViewing/Vnc/VncEncoding.cs
Tight compression levels (which influence zlib compression) and quality levels (which influence JPEG compression quality) are sent over the wire as pseudo-encodings.
Support reading these values.
=> TightEncoder: Support reading compression and quality levels.

RemoteViewing.Tests/Vnc/Server/RawEncoderTests.cs, RemoteViewing.Tests/Vnc/Server/TightEncoderTests.cs, RemoteViewing.Tests/Vnc/Server/ZlibEncoderTests.cs, RemoteViewing/Vnc/Server/RawEncoder.cs, RemoteViewing/Vnc/Server/TightEncoder.cs, RemoteViewing/Vnc/Server/VncEncoder.cs, RemoteViewing/Vnc/Server/VncServerSession.cs, RemoteViewing/Vnc/Server/ZlibEncoder.cs
We'll need this when implementing Tight/JPEG support, as the JPEG encoder needs to be aware of the picture dimensions.
=> Pass the rectangle region to the VNC encoders

RemoteViewing.Tests/Vnc/Server/TightEncoderTests.cs, RemoteViewing/Vnc/Server/TightEncoder.cs
Pitch is expressed in bytes, not pixels, so passing `rectangle.Width` was wrong. When set to `0`, libturbojpeg will auto-determine it, so let's go with that.
=> Tight/JPEG: Make sure the correct pitch is used

RemoteViewing.NoVncExample/DummyFramebufferSource.cs
As a result, the sample image no longer is a rectangle of a single color, which makes it a bit easier to visually spot certain issues.
=> Add text to the dummy framebuffer

RemoteViewing.NoVncExample/DummyFramebufferSource.cs, RemoteViewing.Tests/VncServerSessionTests.cs, RemoteViewing.Windows.Forms/Server/VncScreenFramebufferSource.cs, RemoteViewing/Vnc/ExtendedDesktopSizeReason.cs, RemoteViewing/Vnc/ExtendedDesktopSizeStatus.cs, RemoteViewing/Vnc/Server/VncServerSession.cs, RemoteViewing/Vnc/VncFramebuffer.cs
Implement ExtendedDesktopSize pseudo-encoding and handle the `SetDesktopSize` request.
The `VncServerSession` class can handle the requests at the protocol level, but leaves the actual implementation up to the `IVncFramebufferSource` class.
This change was manually tested using the noVNC client. RealVNC and TightVNC don't seem to handle this pseudo-encoding.
More advanced features, like multi-monitor support, is also not implemented.
Closes #58
=> Implement ExtendedDesktopSize pseudo-encoding 

.azure-pipelines.yml, RemoteViewing.LibVNC.NativeBinaries/RemoteViewing.LibVnc.NativeBinaries.csproj, RemoteViewing.LibVnc.NativeBinaries/mingw32.cmake, RemoteViewing.LibVnc.NativeBinaries/mingw64.cmake, RemoteViewing.LibVnc/RemoteViewing.LibVnc.csproj, RemoteViewing.sln
This is a first step to get build an implementation of RemoteViewing which wraps around the native libvnc library.
This PR adds the RemoteViewing.LibVnc.NativeBinaries package, which contains upstream libvnc compiled for Windows (32-bit and 64-bit) and macOS. Linux users are expected to acquire libvnc through their Linux distribution.
This package is GPLv2 licensed (because libvnc is GPL licensed).
=> Compile LibVNC for Windows and macOS

RemoteViewing.LibVnc.Tests/RemoteViewing.LibVnc.Tests.csproj, RemoteViewing.LibVnc.Tests/RfbScreenInfoPtrTests.cs, RemoteViewing.LibVnc/Interop/NativeLayout.cs, RemoteViewing.LibVnc/Interop/NativeMethods.cs, RemoteViewing.LibVnc/Interop/RfbNewClientAction.cs, RemoteViewing.LibVnc/Interop/RfbPixelFormat.cs, RemoteViewing.LibVnc/Interop/RfbScreenInfoPtr.Fields.cs, RemoteViewing.LibVnc/Interop/RfbScreenInfoPtr.cs, RemoteViewing.LibVnc/Interop/RfbScreenInfoPtrField.cs, RemoteViewing.LibVnc/Interop/RfbSocketState.cs, RemoteViewing.LibVnc/Interop/RfbType.cs, RemoteViewing.LibVnc/RemoteViewing.LibVnc.csproj, RemoteViewing.sln
This PR adds a first draft implementation of the `RfbScreenInfoPtr` class which provides access to the `rfbScreenInfo` struct.
The `rfbScreenInfo` struct is a complex struct, with:
- Fields which may or may not be available based on preprocessor variables
- Fields which have different types depending on the target OS (e.g. sockets on Windows vs. Unix)
- Different alignment rules depending on OS and bitness
Because of this:
- The struct is not represented as a `struct` on the .NET side, but rather as a `SafeHandle` (essentially a wrapper around an `IntPtr`)
- Access to the various field is implemented via properties
The offsets of the individual fields are determined _at runtime_ based on the target OS and bitness. The `RfbScreenInfoPtr` maintains an array which defines the types of all …
=> Prototype the RfbScreenInfoPtr class

.azure-pipelines.yml, RemoteViewing.LibVnc.Tests/RemoteViewing.LibVnc.Tests.csproj, RemoteViewing.Tests/RemoteViewing.Tests.csproj
Apparently code coverage isn't really supposed to work, but it should work soon. Sigh.
https://github.com/microsoft/azure-pipelines-tasks/issues/11677
https://github.com/microsoft/azure-pipelines-tasks/issues/9954
=> Publish code coverage using .trx format, run all unit tests

RemoteViewing.LibVnc.Tests/RfbClientRecPtrTests.cs, RemoteViewing.LibVnc.Tests/RfbScreenInfoPtrTests.cs, RemoteViewing.LibVnc/Interop/NativeCapabilities.cs, RemoteViewing.LibVnc/Interop/NativeLayout.cs, RemoteViewing.LibVnc/Interop/RfbClientRecPtr.Fields.cs, RemoteViewing.LibVnc/Interop/RfbScreenInfoPtr.Fields.cs, RemoteViewing.LibVnc/Interop/RfbType.cs, RemoteViewing.LibVnc/get_offsets.c
The struct layouts are different when using Win32 threading (as opposed to libpthread on Windows). Account for this.
=> Add support for copies of libvncserver compiled with native Win32 threading support

.azure-pipelines.yml, RemoteViewing.LibVnc.Tests/RfbScreenInfoPtrTests.cs, RemoteViewing.LibVnc/Interop/NativeMethods.cs
Instead of cross-compiling to Windows on Ubuntu, just build on Windows natively, using VCPKG for the dependencies.
This has the advantage of:
- Adding libjpeg, libpng and zlib support
- Using the MSVC runtime, keeping things simpler
=> Built on Windows with CMake

RemoteViewing.LibVnc.Tests/RemoteViewing.LibVnc.Tests.csproj, RemoteViewing.LibVnc.Tests/RfbClientRecPtrTests.cs, RemoteViewing.LibVnc.Tests/RfbScreenInfoPtrTests.cs, RemoteViewing.LibVnc/Interop/NativeLayout.cs, RemoteViewing.LibVnc/Interop/RfbClientRecPtr.Fields.cs, RemoteViewing.LibVnc/Interop/RfbScreenInfoPtr.Fields.cs
These are compiled natively on Windows (so use native threading instead of libpthread), and add support for libpng/libjpeg/zlib.
=> Use latest version of the native libraries

RemoteViewing.NoVncExample/DummyFramebufferSource.cs, RemoteViewing.ServerExample/Program.cs
This PR rewrites the VNC Server example:
- The example now uses the `VncServer` class to start the VNC server.
- The demo framebuffer source now acts as a keyboard and mouse controller; the keyboard responds to:
* the `r` key which rotates the screen
* the `+` key which doubles the framebuffer size
* the `-` key which cuts the framebuffer size in half
- The demo framebuffer source now acts as a controller; moving the mouse will now result in the position of the cursor being displayed in the framebuffer.
=> ServerExample: UseVncServer, allow resizing of the framebuffer source

.azure-pipelines.yml, RemoteViewing.LibVnc.Logging/CMakeLists.txt, RemoteViewing.LibVnc.Logging/vnclogger.c, RemoteViewing.LibVnc.NativeBinaries/RemoteViewing.LibVnc.NativeBinaries.csproj
This library acts as a bridge between the C declaration of the logging callback (which uses the `...` - varargs syntax) and .NET, which cannot interop with this.
=> Add (lib)vnclogger.[so|dylib|dll]

RemoteViewing.LibVnc/Interop/NativeLogging.cs, RemoteViewing.LibVnc/Interop/NativeMethods.cs, RemoteViewing.LibVnc/LibVncServer.cs, RemoteViewing.LibVnc/RemoteViewing.LibVnc.csproj, RemoteViewing.ServerExample/Program.cs, RemoteViewing.ServerExample/RemoteViewing.ServerExample.csproj
Enable basic redirection of the logging output from `libvnserver` to an `ILogger` using the `vnclogger` interop library.
The current architecture of `libvncserver` means that log redirection is an all-or-nothing scenario; either _all_ output is redirected to a _single_ logger.
=> Use the vnclogger interop library

RemoteViewing.LibVnc/Interop/RfbScreenInfoPtr.cs, RemoteViewing.LibVnc/LibVncServer.cs, RemoteViewing.NoVncExample/DummyFramebufferSource.cs
This aligns with the pixel format used by the managed implementation.
Extend the DummyFramebufferSource to support displaying an entirely red, green or blue framebuffer - allowing you to double-check color rendering.
=> Use the BGR pixel format

RemoteViewing.LibVnc/Interop/NativeMethods.cs, RemoteViewing.LibVnc/Interop/RfbClientRecPtr.cs, RemoteViewing.LibVnc/LibVncServer.cs
ClientFramebufferUpdateRequestHook was added in https://github.com/LibVNC/libvncserver/commit/5eac9fa4b59d4628b49273dec142ec3e77cd65cb, which is not part of any released version of libvncserver, though it will likely ship in 0.9.13.
Detect 0.9.13 by checking for rfbDefaultSetDesktopSize which was added in https://github.com/LibVNC/libvncserver/commit/8e41510f4a9d449dd228e5b3e29732882f7f5df6, which is also a 0.9.13-only change.
=> Only call ClientFramebufferUpdateRequestHook when supported

RemoteViewing.LibVnc.Logging/vnclogger.c, RemoteViewing.LibVnc/Interop/NativeLogging.cs
Use vasprintf on Linux, and vsprintf when compiling with msvc
=> LibVNC wrapper: Fix logging on Linux

RemoteViewing.LibVnc/Interop/NativeLogging.cs, RemoteViewing.LibVnc/Interop/NativeMethods.cs
Ubuntu ships with `libvncserver.so.1`, and CentOS with`libvncserver.so.0`. Support both.
=> Support versioned library names on Linux

RemoteViewing.LibVnc/Interop/NativeMethods.cs, RemoteViewing.ServerExample/Program.cs, RemoteViewing/RemoteViewing.csproj
- Avoid a NullReferenceException when the native library could not be loaded
- Fix building on non-Windows platforms
- Print out the process ID when starting the demo applications
=> Minor stability fixes

.azure-pipelines.yml, RemoteViewing.AspNetCore/RemoteViewing.AspNetCore.csproj, RemoteViewing.Example/RemoteViewing.Example.csproj, RemoteViewing.LibVnc.NativeBinaries/RemoteViewing.LibVnc.NativeBinaries.csproj, RemoteViewing.LibVnc/RemoteViewing.LibVnc.csproj, RemoteViewing.NoVncExample/RemoteViewing.NoVncExample.csproj, RemoteViewing.ServerExample/RemoteViewing.ServerExample.csproj, RemoteViewing.Windows.Forms/RemoteViewing.Windows.Forms.csproj, RemoteViewing/RemoteViewing.csproj
- Build version 0.9.13
- Disable grcypt, openssl
- Bump Nerdbank.Gitversioning to fix build
=> Check out libvnc 0.9.13 on macOS, build without gcrypt

.azure-pipelines.yml, RemoteViewing.LibVnc.NativeBinaries/RemoteViewing.LibVnc.NativeBinaries.csproj
- Include libjpeg, libpng in the NuGet package
- Drop GNUTLS as a dependency
=> Include missing dependencies on macOS

RemoteViewing.AspNetCore/RemoteViewing.AspNetCore.csproj, RemoteViewing.LibVnc.NativeBinaries/RemoteViewing.LibVnc.NativeBinaries.csproj, RemoteViewing.LibVnc.Tests/RemoteViewing.LibVnc.Tests.csproj, RemoteViewing.LibVnc/RemoteViewing.LibVnc.csproj, RemoteViewing.NoVncExample/RemoteViewing.NoVncExample.csproj, RemoteViewing.NoVncExample/Startup.cs, RemoteViewing.ServerExample/RemoteViewing.ServerExample.csproj, RemoteViewing.Tests/RemoteViewing.Tests.csproj, RemoteViewing.Windows.Forms/RemoteViewing.Windows.Forms.csproj, RemoteViewing/RemoteViewing.csproj
- Drop support for `netstandard2.1`, replace with `netstandard2.0` + `net5.0`
- Add support for `net5.0`
=> Migrate to .NET 5.0

RemoteViewing.Example/RemoteViewing.Example.csproj, RemoteViewing.LibVnc.NativeBinaries/RemoteViewing.LibVnc.NativeBinaries.csproj, RemoteViewing.LibVnc/Interop/NativeLibraryLoader.cs, RemoteViewing.LibVnc/Interop/NativeLogging.cs, RemoteViewing.LibVnc/Interop/NativeMethods.cs, RemoteViewing.LibVnc/LibVncServer.cs, RemoteViewing.LibVnc/RemoteViewing.LibVnc.csproj, RemoteViewing.NoVncExample/bower.json, RemoteViewing.Windows.Forms/RemoteViewing.Windows.Forms.csproj, RemoteViewing.Windows.Forms/VncControl.Designer.cs, RemoteViewing.Windows.Forms/VncControl.cs, RemoteViewing.Windows.Forms/VncKeysym.cs, RemoteViewing/RemoteViewing.csproj
Visual Studio 2022 no longer ships with a targeting pack for .NET 4.5
=> Migrate to .NET 4.6.2 as a the minimum .NET version

RemoteViewing.AspNetCore/VncMiddleware.cs, RemoteViewing.NoVncExample/bower.json
Newer version of noVNC no longer set the requested protocol header, so we should not specify any protocol when calling AcceptWebSocketAsync, either.
=> Bump noVNC to 1.2.0

RemoteViewing.AspNetCore/RemoteViewing.AspNetCore.csproj, RemoteViewing.AspNetCore/VncHandler.cs, RemoteViewing.LibVnc/RemoteViewing.LibVnc.csproj, RemoteViewing.Tests/RemoteViewing.Tests.csproj, RemoteViewing.Windows.Forms/RemoteViewing.Windows.Forms.csproj, RemoteViewing/RemoteViewing.csproj, RemoteViewing/Vnc/Server/TightEncoder.cs
- Drop netstandard2.0 support
- Remove dependency on Nito.AsyncEx
=> Bump TurboJpegWrapper to 2.0.21

RemoteViewing.LibVnc/LibVncServer.cs
No password check will be performed if `LibVncServer.PasswordProvided` is `null`
=> Support running a VncServer using libvnc which does not require a password

RemoteViewing.LibVnc/Interop/NativeMethods.cs
This fixes x86 compatibility issues
=> NativeMethods: Be explicit about calling convention
